### ISSUE TITLE
Bump rustc version and libraries

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#1028]
### Summary
The rust compiler version we currently require is pretty old. We should find and test nightly version corresponding with newest stable version.

The same change should be applied to our rust-lib repo at the same time, see enso-org/rust-lib#1 .

### Acceptance Criteria & Test Cases
Progam compiling and working with updated `rust-toolchain`

**Comment by MichaelMauderer** [comment]
This will first require the same change to be applied to our [rust-lib repo ](https://github.com/enso-org/rust-lib), see https://github.com/enso-org/rust-lib/issues/1 .

**Comment by farmaazon** [comment]
> This will first require the same change to be applied to our [rust-lib repo ](https://github.com/enso-org/rust-lib), see [enso-org/rust-lib#1](https://github.com/enso-org/rust-lib/issues/1) .

True, added to the description.

**Comment by MichaelMauderer** [comment]
Since we had concerns about the time for this task: could we have a separate issue (or progress checkbox) for each of our sub-crates? (Some for the rest-lib repo). We could track which is "nightly-current-read" and some might even be "stable-ready". We could then better track progress and time spent/needed.

**Comment by farmaazon** [comment]
Filled first ICE encountered: https://github.com/rust-lang/rust/issues/84399

**Comment by MichaelMauderer** [comment]
It seems the fix was merged: https://github.com/rust-lang/rust/pull/84472
