### ISSUE TITLE
Check why its impossible to open dev console in running electron process.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/ide#1092]

**Comment by MichaelMauderer** [comment]
This does not seem to be an issue with electron but our event handling. You can actually observe the same behaviour when the IDE runs in the browser: the keyboard shortcut will fail to open the dev console. It can only be opened via the menu. 

This is because we redirect all inputs and don't let them propagate back to the browser, except if you activate a visualization. So if you click on a visualization, you can open the dev console via keyboard shortcuts. Both for the browser and the electron app.

**Comment by farmaazon** [comment]
So, to fix this we should add a shortcut somewhere (perhaps src/rust/ide/view/src/project.rs) and maybe call some function exposed by electron to show the debug console.

**Comment by MichaelMauderer** [comment]
This is one possible workaround, but it only works for the electron use case, but not for the browser use case. Websites are not allowed to open the dev console. Maybe instead we should have a list of keypresses that we allow to propagate, instead of capturing them. This would be more flexible if we encounter other key combinations we want to propagate.

**Comment by MichaelMauderer** [comment]
Actually, it turns out this was a slightly different underlying issue after all: we already have some event handling on the Electron level in `src/js/lib/client/src/index.js` to enable us to toggle the dev tools and quit the app, but it seems that code has been rotten and stopped working due tome electron API changes. Since this is JS it just kept doing its thing, but some variables were undefined and thus just interpreted falsy and no function was provided any more. PR incoming.
