### ISSUE TITLE
Searcher view improvements

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#1553]
### Summary

The searcher should
* be located above all UI elements (except visualizations), but below cursor.
* not be shown if it would be empty.

### Value
Better view of the searcher when creating nodes. Less clutter visible when no information is available. 

### Specification
As above.

### Acceptance Criteria & Test Cases
Manual test scenario. 
Automated test seems unfeasible at the moment as this is mostly visual.

**Comment by wdanilo** [comment]
> Note:
> 
> > be located above all UI elements (except visualizations), but below cursor.
> 
> Might require dynamically changing the layer of the cursor.
> This could be added to the cursor style as a new field that indicates the current layer of the cursor.

Why it would be needed?

**Comment by farmaazon** [comment]
> > Note:
> > > be located above all UI elements (except visualizations), but below cursor.
> > 
> > 
> > Might require dynamically changing the layer of the cursor.
> > This could be added to the cursor style as a new field that indicates the current layer of the cursor.
> 
> Why it would be needed?

Because otherwise we have a "triangle": 
* cursor is currently below node labels (due to port highlighting)
* nodes with their labels should be below searcher
* searcher should be below cursor

So we need to put cursor below node labels only when port are actually highlighted, otherwise it should be kept on top of everything.
