### ISSUE TITLE
Filtering suggestions

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#610]
### Summary
When the Searcher Controller is informed about input change, we should filter the suggestions displayed to user by _pattern_ (see #560). Then Searcher Controller should emit notification about new view of list of suggestions.

### Specification
The filtering algorithm is already implemented in Javascript - @kustosz knows where it is. It has c.a. 200-300 lines of code.. It should be rewritten to rust.

### Acceptance Criteria & Test Cases
Unit tests.

**Comment by kustosz** [comment]
https://github.com/enso-org/fuzzly here's the sources of the original thingy. It's undocumented unfortunately, because it comes from the time our standards were lower (the summer of 2019 was a crazy time, free-coding, hanging out outside...). If you want to talk about how it does what it does, read the code and let's talk later.

<blockquote><img src="https://avatars0.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/fuzzly">enso-org/fuzzly</a></strong></div><div>Fuzzy autocomplete engine. Contribute to enso-org/fuzzly development by creating an account on GitHub.</div></blockquote>

**Comment by wdanilo** [comment]
Ohhh, its a Coffeescript, you will have an amazing time @farmaazon <3
