### ISSUE TITLE
It is impossible to introduce `shift+number` combination in IDE

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#695]
### General Summary

trying to press `Shift` and any number in text editor does not introduce new signs in Text Editor
### Steps to Reproduce

open IDE
try to add new line:
`10 * 2`
### Expected Result

new node `10 * 2`
### Actual Result

`10` and nothing more
### Enso Version

core     : 2.0.0-alpha.0
build    : 14990b4
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by farmaazon** [comment]
I did the quick investigation. Apparently the problem is that the "legacy_keycode" function is used for determine position in mask. Many keys defaults to 0, including `Meta` and... all symbols written by pressing shift+number (`!@#$%^&*()`). Therefore we think that the meta key is pressed and don't write the symbol.

The real solution is to replace old key management with the new done in https://github.com/enso-org/ide/issues/713 . Actually it may be simpler to just replace old TextField with TextEditor 2.0.

The temporary solution is to add exception for those characters where we do the `enables_writing` in `char_typed_lambda` method in ensogl/lib/core/src/display/shape/text/text_field/frp/keyboard.rs
