### ISSUE TITLE
Visualization picker should show just visualizations available for given type

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/ide#837]
### General Summary

For each type in Enso we can define custom set of visualizations available. The visualization picker should show just visualizations available for given type.
### Steps to Reproduce

Open IDE
add node `13`
open visualization
### Expected Result

just text (JSON) visualization
### Actual Result

all visualizations defined are possible to choose but most of them does not work (i.e. geomap)
### Specification

To fix this, we need to implement some simple "type resolution" mechanism:
* Visualization is defined for `Any` type - it should be displayed for any types.
* Visualization is defined for several type alternatives, like `String | Table.Data.Table` - it should be displayed if node's type matches one of the alternatives.
* In other cases visualization is displayed if node's type matches the visualization's type.

The types matches if they fully-qualified names are equal.

The current visualizations should be defined for types:
* JSON - for `Any` type
* Histogram, ScatterPlot - for `Table.Data.Table | Vector`.
* GeoMap - for `Table.Data.Table`.

### Enso Version

core     : 2.0.0-alpha.0
build    : 08849e8
electron : 8.1.1
chrome   : 80.0.3987.141

**Comment by MichaelMauderer** [comment]
I believe implementing this issue requires us to have a better notion of Enso types. At the moment (on our end) they are simple strings that need to be equal. This will most likely not be enough, since we might want to allow visualizations for multiple types of groups of types (e.g., a vector and a data frame). So, do we want to implement some simple rules here, or do we need a proper Enso type resolution library?

Simultaneously we need to coordinate with the engine what types we get, e.g., are there special types for “geolocations” or a “vector of geolocations” in the standard library?

**Comment by farmaazon** [comment]
> I believe implementing this issue requires us to have a better notion of Enso types. At the moment (on our end) they are simple strings that need to be equal. This will most likely not be enough, since we might want to allow visualizations for multiple types of groups of types (e.g., a vector and a data frame). So, do we want to implement some simple rules here, or do we need a proper Enso type resolution library?

Yes, this should be about simple rules. I'll add them to the specification.

> Simultaneously we need to coordinate with the engine what types we get, e.g., are there special types for “geolocations” or a “vector of geolocations” in the standard library?

Yes, there are, or there will be types for them. So the visualizations should be defined for them. I'll try also to summarize them in description.
