### ISSUE TITLE
Pan/zoom works shaky with mouse.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/ide#926]

**Comment by MichaelMauderer** [comment]
This is what happens if I zoom with my mouse wheel (two clicks in, one click out): 

![Peek 2020-11-17 12-48](https://user-images.githubusercontent.com/1428930/99387031-981a4100-28d3-11eb-8cc9-78d2cd355113.gif)

System:
Pop!_OS 20.04 LTS 
Gnome Version 3.36.3 / X11

**Comment by wdanilo** [comment]
I made some initial debug. The results are very interesting, it seems that the navigator uses `event.offset_x()` and `event.offset_y()`, which came directly from `js_sys` and they are sometimes completely crazy values (like once per 10 clicks, `offset_x()` returns me `1` instead of something around `200`. This happens only with mouse events there. It needs to be further debugged and we also need to understand why it doesnt happen with node dragging. I added debug code to `core/src/display/navigation/navigator/events.rs`

**Comment by MichaelMauderer** [comment]
We should clarify the scope of this issue versus enso-org/ide#980. I assumed this issue here was related to what we see in my comment above, which is unrelated to the jumping when the cursor moves over a node, but is a more general issue of scrolling with the mouse wheel.
