### ISSUE TITLE
Dark mode has missing colors

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/ide#991]
### General Summary
Dark mode seems to have missing colours.

### Steps to Reproduce
Open debug scene `debug/interface`.

### Expected Result
Correctly coloured graph editor. 

### Actual Result

![unknown](https://user-images.githubusercontent.com/1428930/100239747-0b562f80-2f32-11eb-82ec-836789d74801.png)

### IDE Version

65acecb3d65f70a62f0abaecdd2049013d9176fa

**Comment by farmaazon** [comment]
BR: The colors were renamed/removed and should be actually bring back from the past commit.

**Comment by BinarySoftware** [comment]
After compiling IDE with changed default color scheme to Dark mode, here are the results:
<img width="1120" alt="Zrzut ekranu 2021-02-8 o 13 54 12" src="https://user-images.githubusercontent.com/26655166/107222740-97e29b00-6a15-11eb-8a18-f6d2da405d0e.png">
Interface debug scene:
<img width="585" alt="Zrzut ekranu 2021-02-8 o 14 44 59" src="https://user-images.githubusercontent.com/26655166/107227906-47bb0700-6a1c-11eb-9c38-57628daafa7f.png">

It seems to me that everything is all right, tested many combinations and didnt see any missing color. Actually no colors can be missing because of how color schemes are defined after refactor by Wojtek.
